const questions = [
    "___?  There's an app for that.",
    "Why can't I sleep at night?",
    "What's that smell?",
    "I got 99 problems but ___ ain't one.",
    "Maybe she's born with it.  Maybe it's ___.",
    "What's the next Happy Meal&copy; toy?",
    "Anthropologists have recently discovered a primitive tribe that worships ___.",
    "It's a pity that kids these days are all getting involved with ___.",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ___.",
    "Alternative medicine is now embracing the curative powers of ___.",
    "And the Academy Award for ___ goes to ___.",
    "What's that sound?",
    "What ended my last relationship?",
    "MTV's new reality show features eight washed-up celebrities living with ___.",
    "I drink to forget ___.",
    "I'm sorry professor, but I couldn't complete my homework because of ___.",
    "What is Batman's guilty pleasure?",
    "This is the way the world ends <br> This is the way the world ends <br> Not with a bang but with ___.",
    "What's a girl's best friend?",
    "TSA guidelines now prohibit ___ on airplanes.",
    "___.  That's how I want to die.",
    "For my next trick, I will pull ___ out of ___.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with ___ for the first time.",
    "___ is a slippery slope that leads to ___.",
    "What does Dick Cheney prefer?",
    "Dear Abby, I'm having some trouble with ___ and would like your advice.",
    "Instead of coal, Santa now gives the bad children ___.",
    "What's the most emo?",
    "In 1,000 years when paper money is but a distant memory, ___ will be our currency.",
    "What's the next superhero/sidekick duo?",
    "In M. Night Shyamalan's new movie, Bruce Willis discovers that ___ had really been ___ all along.",
    "A romantic, candlelit dinner would be incomplete without ___.",
    "___.  Becha can't have just one!",
    "White people like ___.",
    "___.  High five, bro.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of ___.",
    "BILLY MAYS HERE FOR ___.",
    "In a world ravaged by ___, our only solace is ___.",
    "War!  What is it good for?",
    "During sex, I like to think about ___.",
    "What are my parents hiding from me?",
    "What will always get you laid?",
    "In L.A. County Jail, word is you can trade 200 cigarettes for ___.",
    "What did I bring back from Mexico?",
    "What don't you want to find in your Chinese food?",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "How am I maintaining my relationship status?",
    "___.  It's a trap!",
    "Coming to Broadway this season, ___: The Musical.",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ___.",
    "After the earthquake, Sean Penn brought ___ to the people of Haiti.",
    "Next on ESPN2, the World Series of ___.",
    "Step 1: ___.  Step 2: ___.  Step 3: Profit.",
    "Rumor has it that Vladimir Putin's favorite dish is ___ stuffed with ___.",
    "But before I kill you, Mr. Bond, I must show you ___.",
    "What gives me uncontrollable gas?",
    "What do old people smell like?",
    "The class field trip was completely ruined by ___.",
    "When Pharaoh remained unmoved, Moses called down a Plague of ___.",
    "What's my secret power?",
    "What's there a ton of in heaven?",
    "What would grandma find disturbing, yet oddly charming?",
    "I never truly understood ___ until I encountered ___.",
    "What did the U.S. airdrop to the children of Afghanistan?",
    "What helps Obama unwind?",
    "What did Vin Diesel eat for dinner?",
    "___: good to the last drop.",
    "Why am I sticky?",
    "What gets better with age?",
    "___: kid-tested, mother-approved.",
    "What's the crustiest?",
    "What's Teach for America using to inspire inner city students to succeed?",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to ___.",
    "Life for American Indians was forever changed when the White Man introduced them to ___.",
    "Make a haiku.",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with ___.",
    "Why do I hurt all over?",
    "What am I giving up for Lent?",
    "In Michael Jackson's final moments, he thought about ___.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ___.",
    "When I am President of the United States, I will create the Department of ___.",
    "Lifetime&copy; presents ___, the story of ___.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate ___.",
    "When I was tripping on acid, ___ turned into ___.",
    "That's right, I killed ___.  How, you ask?  ___.",
    "What's my anti-drug?",
    "___ + ___ = ___.",
    "What never fails to liven up the party?",
    "What's the new fad diet?",
    "Major League Baseball has banned ___ for giving players an unfair advantage.",
    "My plan for world domination begins with ___.",
    "The CIA now interrogates enemy agents by repeatedly subjecting them to ___.",
    "Dear Sir or Madam, We regret to inform you that the Office of ___ has denied your request for ___",
    "In Rome, there are whisperings that the Vatican has a secret room devoted to ___.",
    "Science will never explain ___.",
    "When all else fails, I can always masturbate to ___.",
    "I learned the hard way that you can't cheer up a grieving friend with ___.",
    "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ___.",
    "An international tribunal has found ___ guilty of ___.",
    "The socialist governments of Scandinavia have declared that access to ___ is a basic human right.",
    "In his new self-produced album, Kanye West raps over the sounds of ___.",
    "What's the gift that keeps on giving?",
    "Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ___ and his wits.",
    "When I pooped, what came out of my butt?",
    "In the distant future, historians will agree that ___ marked the beginning of America's decline.",
    "In a pinch, ___ can be a suitable substitute for ___.",
    "What has been making life difficult at the nudist colony?",
    "Michael Bay's new three-hour action epic pits ___ against ___.",
    "And I would have gotten away with it, too, if it hadn't been for ___.",
    "What brought the orgy to a grinding halt?",
    "During his midlife crisis, my dad got really into ___.",
    "___ would be woefully incomplete without ___.",
    "My new favorite porn star is Joey &#34;___&#34; McGee.",
    "Before I run for president, I must destroy all evidence of my involvement with ___.",
    "This is your captain speaking. Fasten your seatbelts and prepare for ___.",
    "In his newest and most difficult stunt, David Blaine must escape from ___.",
    "The Five Stages of Grief: denial, anger, bargaining, ___, and acceptance.",
    "My mom freaked out when she looked at my browser history and found ___.com/___.",
    "I went from ___ to ___, all thanks to ___.",
    "Members of New York's social elite are paying thousands of dollars just to experience ___.",
    "This month's Cosmo: &#34;Spice up your sex life by bringing ___ into the bedroom.&#34;",
    "Little Miss Muffet Sat on a tuffet, Eating her curds and ___.",
    "If God didn't want us to enjoy ___, he wouldn't have given us ___.",
    "My country, 'tis of thee, sweet land of ___.",
    "After months of debate, the Occupy Wall Street General Assembly could only agree on &#34;More ___!&#34;",
    "I spent my whole life working toward ___, only to have it ruined by ___.",
    "Next time on Dr. Phil: How to talk to your child about ___.",
    "Only two things in life are certain: death and ___.",
    "Everyone down on the ground! We don't want to hurt anyone. We're just here for ___.",
    "The healing process began when I joined a support group for victims of ___.",
    "The votes are in, and the new high school mascot is ___.",
    "Charades was ruined for me forever when my mom had to act out ___.",
    "Before ___, all we had was ___.",
    "Tonight on 20/20: What you don't know about ___ could kill you.",
    "You haven't truly lived until you've experienced ___ and ___ at the same time.",
    "D&D 4.0 isn't real D&D because of the ___.",
    "It's a D&D retroclone with ___ added.",
    "Storygames aren't RPGs because of the ___.",
    "The Slayer's Guide to ___.",
    "Worst character concept ever: ___, but with ___.",
    "Alightment: Chaotic ___",
    "It's a D&D retroclone with ___ added.",
    "What made the paladin fall? ___",
    "The portal leads to the quasi-elemental plane of ___.",
    "The Temple of Elemental ___.",
    "Pathfinder is basically D&D ___ Edition.",
    "___ : The Storytelling Game.",
    "People are wondering why Steve Jackson published GURPS ___.",
    "Linear Fighter, Quadratic ___.",
    "You start with 1d4 ___ points.",
    "Back when I was 12 and I was just starting playing D&D, the game had ___.",
    "Big Eyes, Small ___.",
    "In the grim darkness of the future there is only ___.",
    "My innovative new RPG has a stat for ___.",
    "A true gamer has no problem with ___.",
    "Elminster cast a potent ___ spell and then had sex with ___.",
    "The Deck of Many ___.",
    "You are all at a tavern when ___ approach you.",
    "For the convention I cosplayed as Sailor Moon, except with ___.",
    "The worst part of Grave of the Fireflies is all the ___.",
    "In the Evangelion remake, Shinji has to deal with ___.",
    "Worst anime convention purchase ever? ___.",
    "While powering up Vegeta screamed, ___!",
    "You evaded my ___ attack. Most impressive.",
    "I downloaded a doujin where ___ got into ___.",
    "The magical girl found out that the Power of Love is useless against ___.",
    "The Japanese government has spent billions of yen researching ___.",
    "In the dubbed version they changed ___ into ___.",
    "___ is Best Pony.",
    "The ___ of Haruhi Suzumiya.",
    "The new thing in Akihabara is fetish cafes where you can see girls dressed up as ___.",
    "Your drill can pierce ___!",
    "Avatar: The Last ___ bender.",
    "In the name of ___ Sailor Moon will punish you!",
    "No harem anime is complete without ___.",
    "My boyfriend's a ___ now.",
    "The ___ of ___ has left me in despair!",
    "___.tumblr.com",
    "Somehow they made a cute mascot girl out of ___.",
    "Haruko hit Naoto in the head with her bass guitar and ___ came out.",
    "After blacking out during New year's Eve, I was awoken by ___.",
    "This holiday season, Tim Allen must overcome his fear of ___ to save Christmas.",
    "Jesus is ___.",
    "Every Christmas, my uncle gets drunk and tells the story about ___.",
    "What keeps me warm during the cold, cold, winter?",
    "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and ___.",
    "Wake up, America. Christmas is under attack by secular liberals and their ___.",
    "We got the third rope, now where's the fourth?",
    "Tonights main event, ___ vs. ___.",
    "Tackle, Dropdown, ___.",
    "Christopher Daniels is late on his ___.",
    "Instead of booking ___, they should have booked ___.",
    "Genius is 10% inspiration, 90% ___.",
    "They found ___ in the dumpster behind ___.",
    "The best thing I ever got for Christmas was ___.",
    "There's no crying in ___.",
    "Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! ___!",
    "Don't eat the ___.",
    "He did ___ with the ___!?!",
    "SOOOOO hot, want to touch the ___.",
    "Stop looking at me ___!",
    "I'm cuckoo for ___ puffs.",
    "Silly rabbit, ___ are for kids.",
    "Between love and madness lies ___.",
    "Instead of chess, the Grim Reaper now gambles for your soul with a game of ___.",
    "My father gave his life fighting to protect ___ from ___.",
    "Why is my throat sore?",
    "___ sparked a city-wide riot that only ended with ___.",
    "I’m very sorry Mrs. Smith, but Little Billy has tested positive for ___.",
    "Instead of beating them, Chris Brown now does ___ to women.",
    "Instead of cutting, trendy young emo girls now engage in ___.",
    "The definition of rock bottom is gambling away ___.",
    "The Mayan prophecies really heralded the coming of ___ in 2012.",
    "The next US election will be fought on the key issues of ___ against ___.",
    "When I was 10 I wrote to Santa wishing for ___.",
    "Where or How I met my last signifigant other: ___.",
    "___, Never leave home without it.",
    "___. This is my fetish.",
    "David Icke's newest conspiracy theory states that ___ caused ___.",
    "I did ___ so you don't have to!",
    "I need your clothes, your bike, and ___.",
    "In a new Cold War retro movie, the red menace tries to conquer the world through the cunning use of ___.",
    "In college, our lecturer made us write a report comparing ___ to ___.",
    "In The Hangover part 3, those four guys have to deal with ___, ___, and ___.",
    "My zombie survival kit includes food, water, and ___.",
    "The way to a man's heart is through ___.",
    "What was the theme of my second wedding?",
    "What's the newest Japanese craze to head West?",
    "Everybody loves ___.",
    "I can only express myself through ___.",
    "My new porn DVD was completely ruined by the inclusion of ___",
    "My three wishes will be for ___, ___, and ___.",
    "The latest horrifying school shooting was inspired by ___.",
    "I got fired because of my not-so-secret obsession over ___.",
    "My new favourite sexual position is ___",
    "A successful job interview begins with a firm handshake and ends with ___.",
    "Lovin' you is easy 'cause you're ___.",
    "My life is ruled by a vicious cycle of ___ and ___.",
    "The blind date was going horribly until we discovered our shared interest in ___.",
    "___. Awesome in theory, kind of a mess in practice.",
    "I'm not like the rest of you. I'm too rich and busy for ___.",
    "In the seventh circle of Hell, sinners must endure ___ for all eternity.",
    "___: Hours of fun. Easy to use. Perfect for ___!",
    "What left this stain on my couch?",
    "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ___ in the workplace.",
    "When you get right down to it, ___ is just ___.",
    "Turns out that ___-Man was neither the hero we needed nor wanted.",
    "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ___.",
    "Money can't buy me love, but it can buy me ___.",
    "With enough time and pressure, ___ will turn into ___.",
    "And what did you bring for show and tell?",
    "During high school, I never really fit in until I found ___ club.",
    "Hey, baby, come back to my place and I'll show you ___.",
    "After months of practice with ___, I think I'm finally ready for ___.",
    "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ___.",
    "Finally! A service that delivers ___ right to your door.",
    "My gym teacher got fired for adding ___ to the obstacle course.",
    "Having problems with ___? Try ___!",
    "As part of his contract, Prince won't perform without ___ in his dressing room.",
    "Listen, son. If you want to get involved with ___, I won't stop you. Just steer clear of ___.",
    "I just met you and this is crazy, but here's ___, so ___ maybe",
    "It's only ___ if you get caught!",
    "___: The Next Generation",
    "Terminator 4: ___",
    "Disney presents ___ on ice!",
    "___. The other white meat.",
    "A ___ a day keeps the ___ away.",
    "I'm sweating like a ___ at a ___.",
    "I love the smell of ___ in the morning.",
    "You're not gonna believe this, but ___.",
    "___. All the cool kids are doing it.",
    "So I was ___ in my cubicle at work, and suddenly ___!",
    "Baskin Robbins just added a 32nd flavor: ___!",
    "I can drive and ____________ at the same time.",
    "___ ain't nothin' to fuck wit'!"
];
